# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bODC5FVmYVUKus1zgGWBOCFRQFx0oIOq
"""

import cv2 as cv
from PIL import Image
from skimage.metrics import structural_similarity
import imutils

real=Image.open('/fake-pan-card_yourspj.jpg')
fake=Image.open('/content/pan-card-fake.png')
real=real.resize((500,300))
fake=fake.resize((500,300))

fake.save('/content/pan-card-fake.png')
real.save('/fake-pan-card_yourspj.png')
fake

real

fake=cv.imread('/content/pan-card-fake.png')
real=cv.imread('/fake-pan-card_yourspj.png')

gray_fake=cv.cvtColor(fake,cv.COLOR_BGR2GRAY)
gray_real=cv.cvtColor(real,cv.COLOR_BGR2GRAY)

(score,diff)=structural_similarity(gray_real,gray_fake,full=True)
diff=(diff*255).astype("uint8")
print("SSIM:{}".format(score))

thresh=cv.threshold(diff,0,255,cv.THRESH_BINARY_INV|cv.THRESH_OTSU)[1]
cnts=cv.findContours(thresh.copy(),cv.RETR_EXTERNAL,cv.CHAIN_APPROX_SIMPLE)
cnts=imutils.grab_contours(cnts)

for c in cnts:
  (x,y,w,h)=cv.boundingRect(c)
  cv.rectangle(real,(x,y),(x+w,y+h),(0,0,255),2)
  cv.rectangle(fake,(x,y),(x+w,y+h),(0,0,255),2)

Image.fromarray(real)

Image.fromarray(fake)

Image.fromarray(diff)

Image.fromarray(thresh)